name: Release Hotcakes Core

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/semantic-release.yml
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
