name: Release Hotcakes Core

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    uses: ./.github/workflows/semantic-release.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
