name: Release Hotcakes Core

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/semantic-release.yml
    secrets: inherit
    with:
      repository: ${{ github.repository }}
