name: Semantic Release

on:
  workflow_call:
    inputs:
      github-token:
        description: The NPM Token that lets you interace with github repos
        required: true
        type: string
      npm-token:
        description: The NPM Token that lets you publish to the npm registry
        required: true
        type: string

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
          NPM_TOKEN: ${{ inputs.npm-token }}
        run: npx semantic-release
